#!/bin/bash


# Author: Loretta Adjei
# Date Created: 21/06/2023
# Date Modified: 21/06/2023

# Description 
# Create a backup in ~/bash_course folder of all files in the home directory

# Usage 
# backup_script

echo "Hello, ${USER^}"
echo "I will now backup your home directory, $HOME"

currentdir=$(pwd)
echo "You are running this script from $currentdir"
echo "Therefore, I will save the backup in $currentdir"



tar -cf $currentdir/my_backup_"$(date +%d-%m-%Y_%H-%m-%s)".tar $HOME/* 2>/dev/null
echo "Backup completed successfully"
exit 0
